version: "3.9"
services:
  backend:
    build: .
    ports: 
      - "8000:8000"
    links: 
      - database
  database:
    image: django
    ports:
      - "8001:8001"
    # volumes:
    #   - sqlite3-data:/lib/db.sqlite3

# volumes:
#   sqlite3-data: